name: Generate File Tree

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-tree:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Generate file tree JSON
      run: |
        python3 -c "
        import os
        import json
        
        def build_tree(directory):
            tree = {}
            try:
                for item in sorted(os.listdir(directory)):
                    if item.startswith('.') or item in ['fileTree.json', 'README.md', 'index.html', 'styles.css', 'script.js']:
                        continue
                        
                    item_path = os.path.join(directory, item)
                    
                    if os.path.isdir(item_path):
                        tree[item] = {
                            'type': 'folder',
                            'children': build_tree(item_path)
                        }
                    else:
                        tree[item] = {
                            'type': 'file',
                            'path': item_path,
                            'extension': os.path.splitext(item)[21][1:] if '.' in item else ''
                        }
            except PermissionError:
                pass
            return tree
        
        file_tree = build_tree('.')
        with open('fileTree.json', 'w') as f:
            json.dump(file_tree, f, indent=2)
        "
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add fileTree.json
        if ! git diff --staged --quiet; then
          git commit -m "Auto-update file tree [skip ci]"
          git push
        fi
